new_deals = "id@@ar-new-deal-button"
select_profile_btn = "id@@mui-component-select-profile"
assure_standard_type = "id@@ar-btn-select-standard"
enter_deal_details= "id@@ar-btn-enter-deal-details"
deal_name_field = "xpath@@//input[@name='name']"
deal_logo_field = "xpath@@//div[@id='dropzone']//input"
deal_desc_field = "xpath@@//div[@aria-label='rdw-editor']"
target_amount = "xpath@@//input[@name='targetRaiseAmount']"
mini_invest_amnt = "xpath@@//input[@name='minInvestmentAmount']"
carry_percent = "xpath@@//input[@name='organizerCarryPercentage']"
close_date = "xpath@@//input[@name='estimatedCloseDate']"
deal_gen_doc = "xpath@@//button[@id='ar-btn-generate-doc']"
deal_suc_alert = "xpath@@//div[@role='dialog']"
messge = "xpath@@//div[@class='swal-title']"
ok_btn = "xpath@@//button[contains(@class,'swal-button--confirm')]"
review_accept = "id@@ar-check-reveiew-acceptance"
approval_btn = "xpath@@//h6[contains(text(),'Approve')]"
skip_step = "xpath@@//h5[text()='Skip this step.']"