new_deals = "id@@ar-new-deal-button"
select_profile_btn = "id@@mui-component-select-profile"
assure_standard_type = "id@@ar-btn-select-standard"
assure_labs_type = "id@@ar-btn-select-as.Labs"
enter_deal_details= "id@@ar-btn-enter-deal-details"
deal_name_field = "xpath@@//input[@name='name']"
deal_logo_field = "xpath@@//div[@id='dropzone']//input"
deal_desc_field = "xpath@@//div[@aria-label='rdw-editor']"
target_amount = "xpath@@//input[@name='targetRaiseAmount']"
mini_invest_amnt = "xpath@@//input[@name='minInvestmentAmount']"
carry_percent = "xpath@@//input[@name='organizerCarryPercentage']"
close_date = "xpath@@//input[@name='estimatedCloseDate']"
deal_gen_doc = "xpath@@//button[@id='ar-btn-generate-doc']"
deal_suc_alert = "xpath@@//div[@role='dialog']"
messge = "xpath@@//div[@class='swal-title']"
ok_btn = "xpath@@//button[contains(@class,'swal-button--confirm')]"
review_accept = "id@@ar-check-reveiew-acceptance"
approval_btn = "xpath@@//h6[contains(text(),'Approve')]"
skip_step = "xpath@@//h5[text()='Skip this step.']"
add_assign = "xpath@@//div[contains(@class,'jss454')]//div[text()='Add assignment']"
deal_detail_sec = "xpath@@//h6[text()='Deal details']"
carry_sec = 'xpath@@//h6[text()="Carry"]'
carry_edit_btn = "xpath@@//*[name()='svg' and @id='carry-edit']"
bank_de_sec = "xpath@@//h6[text()='Bank details']"
mngment_fee_sec = "xpath@@//h6[text()='Management fees']"
edit_mng_fee_btn = "xpath@@//*[name()='svg' and @id='edit-11']"
percentange_field = "xpath@@//input[@value='percent']"
flat_fee_field = "xpath@@//span[text()='Flat fee']"
mngmnt_perc_input = "xpath@@//input[@name='percent']"
flat_fee_input = "xpath@@//input[@name='flat']"
mngnt_fee_save_n_cls_btn = "xpath@@//span[text()='Save and close']"
investor_sec = "xpath@@//div[contains(@class,'jss418')]//p[text()='Investors']"
overview_sec= "xpath@@//div[contains(@class,'jss418')]//p[text()='Overview']"
docs_sec = "xpath@@//div[contains(@class,'jss418')]//p[text()='Docs']"
trns_sec = "xpath@@//div[conatains(@class,'jss418')]//p[text()='Transactions']"
deals = "xpath@@//div[@id='open']//p[text()='OPEN']"
editor_dialog = "xpath@@//div[@id='customized-dialog-title']"
invite_p = "xpath@@//span[text()='Invite']/ancestor::button"
invite_investor = "xpath@@//h4[text()='Invite investors to this deal']"
invite_mail_input= "xpath@@//label[@id='state-select']/parent::div//input"
sent_invite_btn = "xpath@@//button[@id='ar-btn-send-invite']"
succes_msg = "xpath@@//h3[text()='Invitation succesfully sent!']"
downloads_doc = "xpath@@//div[contains(@class,'jss502')]//*[name()='svg']"

