cookie_accept ="id@@hs-eu-confirmation-button"
alread_have_an_accnt =  "id@@ar-btn-already-an-account"
setting_icon = "xpath@@//div[@id='basic-button']//p"
profile_sec = "xpath@@//li[@id='profiles--mobile']"
new_profiles = "xpath@@//span[contains(text(),'New')]/ancestor::button"
