new_profile_btn = "xpath@@//button[@id='ar-new-deal-button-profile']"
first_name = "xpath@@//input[@name='firstName']"
last_name = "xpath@@//input[@name='lastName']"
loaded_mail = "xpath@@//input[contains(@value,'@')]"
email = "xpath@@//input[@name='email']"
phone_number = "xpath@@//input[@id='phone-any-11']"
address_1 = "xpath@@//input[@name='address1']"
address_2 = "xpath@@//input[@name='address2']"
city = "xpath@@//input[@name='city']"
country = "xpath@@//input[@name='country']"
state = "xpath@@//input[@name='state']"
ala = "xpath@@//li[contains(text(),'Alabama')]"
postal_code = "xpath@@//input[@name='postalCode']"
date_of_birth = "xpath@@//input[@name='dateOfBirth']"
profiles_dlt_btn = "xpath@@//tr[@role='checkbox']//td[11]/*[name()='svg']"
us_yes = "xpath@@//div[@id='1.1i']//input[@value='yes']|//input[@value='yes']"
ssn_input = "xpath@@//input[@name='ssnNumber']"
# no_click = "xpath" "//span[@class='MuiIconButton-label']/input[@value='no']"
# create_profile = "xpath@@//div[@class='MuiBox-root jss335']/ancestor::span"
create_individual = 'xpath@@//button[@id="submit--individual-profile"]'
investor_accreditation_btn = "xpath@@//*[name()='svg' and @class='jss268']"
accreditation_option1 = "xpath@@//input[@id='check-box-1']/parent::span"
accreditation_option2 = "xpath@@//input[@id='check-box-2']/parent::span"
create_profile = "xpath@@//button[@type='submit']"
create_profile_ent = "xpath@@//*[contains(text(),'Create profile')]/parent::button"
invdividual_profile_dlt_btn = "xpath@@//td[text()='INDIVIDUAL']/parent::tr//td[11]/*[name()='svg']"
delete_success_pop = "xpath@@//div[@role='dialog']"
close_dialog = "xpath@@//button[@class='swal-button swal-button--confirm']"
entity_profile_sec = "xpath@@//div[contains(@class,'jss166')]"
entiy_profile_selected = "xpath@@//div[contains(@class,'jss166')]//h6[contains(@class,'jss155')]"
entity_name_input = "xpath@@//input[@name='name']"
ein_input = "xpath@@//input[@name='taxId']"
add_signatory_btn = 'xpath@@//button[@id="id--add-signatory"]'
add_signatory_txt = "xpath@@//h5[contains(@class,'jss312')] | //h5[contains(@class,'jss315')]"
signatory_title = "xpath@@//input[@name='title']"
signatory_add1 = "xpath@@//input[@name='signatoryAddress1']"
signatory_add2 = "xpath@@//input[@name='signatoryAddress2']"
signatory_postal_code = "xpath@@//input[@name='signatoryPostalCode']"
sign_city_input = "xpath@@//input[@name='signatoryCity']"
sign_state_input = "xpath@@//input[@name='signatoryState']"
sign_country_input = "xpath@@//input[@name='signatoryCountry']"
sig_us_cit_yes = "xpath@@//label[@id='1.1ef']"
save_signatory_btn = "xpath@@//button[@id='save-entity-primary-signatory']"
save_cre_entity_p_btn = "xpath@@//button[@id='submit-inv--entity']"
entity_accr = "xpath@@//div[contains(@class,'jss376')] |//*[name()='svg' and @class='jss380']"
delete_btn_for_entity = "xpath@@//td[contains(text(),'New_entity_profile')]/parent::tr//td[11]/*[name()='svg']"

trust_p_sec = "xpath@@//div[contains(@class,'jss171')]"
trust_p_selected = "xpath@@//div[contains(@class,'jss171')]//h6[contains(@class,'jss155')]"
trust_name = "xpath@@//input[@name='name']"
signer_us = "xpath@@//div[@id='1.1t']//input[@value='yes']"
signer_title = "xpath@@//input[@name='title']"
submit_trust_p = "xpath@@//button[@id='submit--trust-profile']/parent::a"
trust_accre = "xpath@@//div[contains(@class,'jss324')]"
delete_btn_for_trust = "xpath@@//td[contains(text(),'TrustProfile')]/parent::tr//td[11]/*[name()='svg']"

joint_p_sec = "xpath@@//div[contains(@class,'jss173')]//h6"
joint_p_selected ="xpath@@//div[contains(@class,'jss173')]//h6[contains(@class,'jss155')]"
joint_d_name="xpath@@//input[@name='displayName']"
joint_signer_us = "xpath@@//label[@id='1.1f']//input[@value='yes']"
add_joint_signatory_btn = "xpath@@//button[@id='add--joint--signatory']"
signatory_fname="xpath@@//input[@id='add-sig-fn']"
signatory_lname= "xpath@@//input[@id='add-sig-ln']"
signatory_email = "xpath@@//input[@id='add-sig-em']"
signatory_joint_save_btn = "xpath@@//button[@id='add-sig-save-btn']"
joint_accre_btn = "xpath@@//button[@id='submit--joint']"
joint_accre_op = "xpath@@//div[contains(@class,'jss377')]"
joint_profile_dlt_btn = "xpath@@//td[contains(text(),'New_joint_profile')]/parent::tr//td[11]/*[name()='svg']"

retirement_sec = "xpath@@//h6[text()='Retirement']"
retirement_sec_selected ="xpath@@//h6[text()='Retirement' and contains(@class,'jss155')]"
retire_us_city = "xpath@@//div[@id='1.1r']//input[@value='yes']"

IRA = "xpath@@//label[@id='1.7rf']"
FOUR0K1 = "xpath@@//label[@id='1.8rf']"
submit_retire_profile = "xpath@@//button[@id='id-profile--retirement']"
retirement_next_btn = "xpath@@//button[@id='profile--next-retirement']"
retire_acreditation = "xpath@@//div[contains(@class,'jss324')]"
retirement_profile_dlt_btn = "xpath@@//td[contains(text(),'RETIREMENT')]/parent::tr//td[11]/*[name()='svg']"

entity_type_selecion = "xpath@@//div[@id='mui-component-select-entityType']"
LIMITED_PARTNER  ="xpath@@//li[@data-value='LIMITED_PARTNERSHIP']"


not_us_btn = "xpath@@//label[@id='1.2rf']//input[@value='no']"