username_field = "id@@username"
pwd_field = "id@@password"
sign_in = "id@@kc-login"
settings_icon = "xpath@@//div[@id='root']//div[@id='basic-button']"
warning_msg = "xpath@@//span[@class='kc-feedback-text']"
login_header = "xpath@@//form[@id='kc-form-login']"
h1 = "xpath@@//input[@id='kc-login']"