username_field = "id@@username"
pwd_field = "id@@password"
sign_in = "id@@kc-login"
settings_icon = "xpath@@//div[@id='root']//div[@id='basic-button']"
warning_msg = "xpath@@//span[@class='kc-feedback-text']"
login_header = "xpath@@//header[@class='login-pf-header']"
h1 = "xpath@@//h1/span"