new_profiles_btn = "xpath@@//span[text()='New profile']/ancestor::button"
new_org_profile = "xpath@@//h4[text()='New organizer profile']"
individual_p = "xpath@@//p[text()='Individual']"
create_individual_btn = "xpath@@//a[contains(@href,'create-individual')]"
auth_tax_res_fname= "xpath@@//input[@name='taxFirstName']"
auth_tax_res_lname = "xpath@@//input[@name='taxLastName']"
auth_tax_res_add1 = "xpath@@//input[@name='taxAddress1']"
auth_tax_res_add2 = "xpath@@//input[@name='taxAddress2']"
auth_tax_res_city = "xpath@@//input[@name='taxCity']"
auth_tax_res_ssn ="xpath@@//input[@name='taxIdentificationNumber']"
auth_tax_dob = "xpath@@//input[@name='taxDateOfBirth']"
auth_tax_res_state= "xpath@@//input[@name='taxState']"
ala = "xpath@@//li[contains(text(),'Alabama')]"

create_individual_profile_btn = "xpath@@//button[@id='ar-btn-create-ind-prof']"